# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: "14.x"
  displayName: "Install Node.js"

- script: yarn
  displayName: yarn install

- script: yarn nx run-many --target=build --all
  displayName: "Nx - Build All Projects"

- script: yarn nx run-many --target=test --projects=sonar-cloud --codeCoverage --coverageDirectory='./coverageReports' 
  displayName: "Nx - Test All Projects"

# - script: yarn nx affected --target=lint
#   displayName: "Nx - Run Affected Linting"

# - script: yarn nx affected --target=test --reporters=jest-junit --ci --parallel=3 --codeCoverage
#   displayName: "Nx - Run Affected Tests and Get Coverage"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: 'umerkha2007'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'umerkha2007_MobxInNx'
    cliProjectName: 'MobxInNx'
    cliSources: '.'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '5000'
