# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: 'umerkha2007'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'umerkha2007_MobxInNx'
    cliProjectName: 'MobxInNx'
    cliSources: '.'
    extraProperties: |
      sonar.javascript.lcov.reportPaths=$(System.DefaultWorkingDirectory)/coverageReports/lcov.info

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '5000'
